framework:
    default_locale: hu
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - hu
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
#            phrase:
#                dsn: '%env(PHRASE_DSN)%'
