services:
  mysql:
    image: mariadb:12
    container_name: mysql
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: miserend
    healthcheck:
      test: [CMD, mariadb-admin, ping, -h, localhost, -u, user, -ppw]
      timeout: 5s
      retries: 10
    networks:
      inner:
        aliases:
          - mysql
  data-init:
    image: ghcr.io/krisek/miserend-elasticsearch-data:2026.2.9
    volumes:
      - elasticsearch_data:/data
    restart: "no"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - cluster.name=miserend
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    depends_on:
      - data-init
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      inner:
        aliases:
          - elasticsearch
  tmp-init:
    image: busybox
    volumes:
      - tmp:/data
    command: sh -c "chown -R 33:33 /data"

  miserend:
    container_name: miserend
    image: ghcr.io/borazslo/miserend.hu:v2026.1.14
    volumes: 
       - tmp:/miserend/webapp/fajlok/tmp
    ports:
      - 8000:8000
    user: "www-data"
    depends_on:
      - mysql
      - tmp-init
      - elasticsearch

    environment: []
    networks:
      inner:
        aliases:
          - miserend
networks:
  inner:
    driver: bridge
volumes:
  db_data: {}
  elasticsearch_data: {}
  tmp: {}
