purge:
  columns:
    templomok:
      - adminmegj
      - kontakt
      - kontaktmail
      - log
      - letrehozta
      - modositotta
  tables:
    - chat
    - church_holders
    - favorites
    - emails
    - remarks
    - user
    - boundaries
    - distances
    - lookup_boundary_church
    - lookup_church_osm
    - osm
    - messages
    - osmtags
    - stats_externalapi
    - tokens
